### ISSUE TITLE
打开debug正常不报错，关闭debug就报错！

### ISSUE THREAD

**Issue by lzlshow** [zhongshaofa/easyadmin#119]
echarts.min.js?v=2.0.0:25 Uncaught TypeError: Cannot read properties of null (reading 'nodeName')
at new b (/static/plugs/echarts/echarts.min.js?v=2.0.0:25:21693)
at new p (/static/plugs/echarts/echarts.min.js?v=2.0.0:23:587)
at Object.f.init (/static/plugs/echarts/echarts.min.js?v=2.0.0:23:151)
at new r (/static/plugs/echarts/echarts.min.js?v=2.0.0:1:4219)
at Object.st.init (/static/plugs/echarts/echarts.min.js?v=2.0.0:10:6919)
at Object.welcome (/static/admin/js/index.js?v=2.0.0:67:42)
at eval (eval at (config-admin.js:38:13), :1:12)
at config-admin.js:38:13
at Object.execCb (require.js:5:16727)
at e.check (require.js:5:10499)

打开debug正常不报错，关闭debug就报错！
这个应该是统计报表这个地方报错的吧
我把welcome中的的报表统计注释掉及index.js中的统计报表也一起注释掉后还是报错，单独打开welcome页面还是报错，我找了一天实在找不出办法，加QQ群让加三群，三群加了半天也没有通过，加你QQ了，不知道何时才能退过啊！

**Comment by wubiandaxian** [comment]
系统设置里，改下系统版本号，清下缓存试试，关闭debug时，访问的js都是缓存的js
